Ports/cartesi
cartesi/opensbi pull request #1
Opened 2023-06-22 18:45 UTC by mpolitzer

Cartesi port.

On top of https://github.com/cartesi/opensbi/commit/6b5188ca14e59ce7bf71afe4e7d3d557c3d31bf8 `v1.2` (upstream)

2023-07-03 16:38 UTC, alexmikhalevich commented on platform/cartesi/platform.c
> +	.ipi_init		= fdt_ipi_init,
if we are using `fdt_ipi_init` here to have a possibility to mess with it in the future, I think it also makes sense to use `fdt_ipi_exit` here just to make things cleaner

2023-07-03 16:38 UTC, alexmikhalevich commented on platform/cartesi/platform.c
> +	.timer_init		= fdt_timer_init,
should we also add `fdt_timer_exit` here?

2023-07-03 16:38 UTC, alexmikhalevich commented on platform/cartesi/platform.c
> +const struct sbi_platform_operations platform_ops = {
there exists a `get_tlbr_flush_limit` operation. it is not strictly necessary, but we may want to play with this value. I would propose to borrow @edubart brain for this. Here is the [comment about this operation](https://github.com/cartesi/opensbi/blob/dc1c7db05e075e0910b93504370b50d064a51402/include/sbi/sbi_platform.h#L301) for reference.

2023-07-03 17:17 UTC, mpolitzer commented on platform/cartesi/platform.c
> +const struct sbi_platform_operations platform_ops = {
Added[1]. The rest of the function was just a hook that we wouldn't use.

[1]
```
static u64 platform_tlbr_flush_limit(void)
{
	return SBI_PLATFORM_TLB_RANGE_FLUSH_LIMIT_DEFAULT;
}
```

2023-07-03 17:35 UTC, edubart commented on platform/cartesi/platform.c
> +const struct sbi_platform_operations platform_ops = {
The default of `SBI_PLATFORM_TLB_RANGE_FLUSH_LIMIT_DEFAULT=4096` seems appropriate. We don't support flushing single TLB entries, so at this moment playing with this value will not give any benefit.

2023-07-03 17:58 UTC, edubart commented on platform/cartesi/platform.c
> +	.platform_version	= SBI_PLATFORM_VERSION(0x0, 0x00),
I think we could use this to identify release versions of our OpenSBI from inside the machine, and every new OpenSBI release we bump it. Maybe define the version in the makefile like we did with emulator.

2023-07-05 14:00 UTC, edubart requested changes

2023-07-05 14:00 UTC, edubart commented on platform/cartesi/htif.c
> +static void cartesi_htif_system_reset(u32 type, u32 reason)
I was experimenting removing ROM while using OpenSBI, and when I try to initialize OpenSBI with an invalid FDT, it will fail in `sbi_trap_error` and ultimately call `sbi_hart_hang`:

```c++
void __attribute__((noreturn)) sbi_hart_hang(void)
{
	while (1)
		wfi();
	__builtin_unreachable();
}
```

Seems like this function `sbi_hart_hang` is raised for many fatal errors, at this moment this hang function will loop forever, can you modify it to do something like `cartesi_htif_system_reset` is doing here? So the machine halts with an error status.

`_start_hang` in `fw_base.S` could also have this:

```asm
_start_hang:
	wfi
	j	_start_hang
````

2023-07-05 14:43 UTC, mpolitzer commented
Hi @edubart, I've attached a patch (txt because github won't let me use the .patch extension) that should do what you asked (but is untested).

It looks like `a0` and `a1` are being kept unchanged, so it should give: (0,1) in case of a hang.
I'll look into making those return values robust, instead of just inspecting the `asm`.

Do you think we should add this to the final port?
Probably makes sense since there is no poing in looping forever in an emulator.

[0001-hijack-hang.txt](https://github.com/cartesi/opensbi/files/11959046/0001-hijack-hang.txt)

2023-07-10 17:45 UTC, edubart commented
> Do you think we should add this to the final port?

Yes, I think makes sense. I am hitting lots of loop forever issues when something fails, and things are failing frequently while I am developing boot related changes.

I am having another issue with this PR, yield does not work, example:

```
$ cartesi-machine --htif-yield-automatic --quiet -i yield automatic progress
ERR: Failed stop hart [0]
```

Old ROM works.

2023-07-10 19:39 UTC, edubart commented on platform/cartesi/platform.c
> +	.platform_version	= SBI_PLATFORM_VERSION(0x0, 0x00),
Hmm second thought, not needed because kernel and image version will already bundles this.

2023-08-28 14:26 UTC, alexmikhalevich approved these changes

2023-08-28 16:39 UTC, edubart commented on platform/cartesi/htif.c
> +	(void)htif->fromhost; // read and discard the value
Won't this be optimized out?

2023-08-30 13:50 UTC, mpolitzer commented on platform/cartesi/htif.c
> +	(void)htif->fromhost; // read and discard the value
No, `htif` is defined as `volatile`.

2023-08-30 16:36 UTC, edubart commented on platform/cartesi/htif.c
> +	(void)htif->fromhost; // read and discard the value
Oh, right

2023-08-30 16:36 UTC, edubart approved these changes

2023-09-25 19:34 UTC, mpolitzer commented
Code got integrated into the `opensbi-1.2-ctsi-y` branch. Closing this PR.

2023-09-25 19:34 UTC, closed without merging